### PR TITLE
CSHARP-2640: Test MongoDB 4.2 in Evergreen

### PR DESCRIPTION
**Pull request by ksadoff**
https://jira.mongodb.org/browse/CSHARP-2640
Evergreen patch: https://evergreen.mongodb.com/version/5d2382f2e3c33123fcd6e07b

Ready for review.

### CODE REVIEW

**Review by vincentkam — APPROVED** [review]
Looks good to me 😸

**Review by DmitryLukyanov — APPROVED** [review]
LGTM

**Review by rstam — APPROVED** [review]
LGTM

**Comment by ksadoff** [comment]
Rebased, merged, and pushed.

**Pull request closed without merging**
